##
## EPITECH PROJECT, 2024
## Makefile
## File description:
##
##
NAME = 104neutrinos

all:
		chmod +x $(NAME)

clean:
		rm -f *.o

fclean: clean
		rm -f a.out
		rm -f $(NAME)
		rm -f *~
		rm -f lib/my/libmy.a
		rm -f lib/my/*.o
		rm -f lib/my/*~
		rm -f coding-style-reports.log
		rm -f *.gcno
		rm -f *.gcda
		rm -f unit_tests
		rm -f *.out

re: fclean all
